### ISSUE TITLE
Contrato com o micro serviço de Fatura

### ISSUE THREAD

**Issue by Ar3secchim** [Ar3secchim/Channel-Subscription-Service#5]
O objetivo desta issue é implementar a funcionalidade que permite a atualização dinâmica de faturas quando novos canais são adicionados a uma assinatura existente. Isso envolve a comunicação entre o serviço de assinaturas e o microserviço de faturas para garantir que as alterações nos pacotes de canais sejam refletidas com precisão nas faturas subsequentes.

Tarefas:

- [ ]  Conversar com o squad do microserviço de faturas para alinhar os requisitos e garantir uma implementação consistente.
- [ ] Elaborar um contrato ou especificação técnica que detalhe a comunicação entre o serviço de assinaturas e o microserviço de faturas.
- [ ] Implementar a notificação de criação de um pacote no serviço de assinaturas, de modo que o microserviço de faturas seja informado imediatamente sobre as alterações na assinatura do usuário.
- [ ]  Atualizar a lógica do microserviço de faturas para processar e refletir dinamicamente as alterações nos pacotes de canais nas faturas existentes e futuras.

**Comment by LucianaXarim** [comment]
Essa task será arquivada, pois o serviço de fatura fará a busca dos pacotes/usuários de forma periodica nao fazendo sentido o envio dos novos pacotes de forma dinâmica.
